config/routes.rb
Porra::Application.routes.draw do

  root 'welcome#index'
  resources :combinis
  resources :typegroups do
    resources :combinis
  end
  resources :types
  post '/login', to: 'users#login'
  
  resources :users

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	has_many :achievement_user
	has_many :users, through: :achievement_user
end

app/models/achievement_user.rb
class AchievementUser < ActiveRecord::Base
	has_many :users
	has_many :achievements
end

app/models/combini.rb
class Combini < ActiveRecord::Base
	belongs_to :user
	belongs_to :type
	belongs_to :typegroup
	belongs_to :neighborhood
	has_many :likes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :combini
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
	belongs_to :user
	belongs_to :type
	belongs_to :typegroup
	has_many :likes
end

app/models/inventory.rb
class InventoryItem < ActiveRecord::Base
	has_many :products
	has_many :users
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :complaint
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
	has_many :combinis
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_category
	has_many :inventory_items
	has_many :users, through: :inventory_items
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	has_many :products
end

app/models/title.rb
class Title < ActiveRecord::Base
	has_many :users
end

app/models/type.rb
class Type < ActiveRecord::Base
	belongs_to :typegroup
	has_many :combinis
end

app/models/typegroup.rb
class Typegroup < ActiveRecord::Base
	has_many :types
	has_many :combinis
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :combinis
	has_many :likes
	has_many :comments
	has_many :products, through: :inventory_items
	has_many :inventory_items
	belongs_to :title
	has_many :achievements, through: :achievement_users
	has_many :achievement_users
end

app/controllers/combinis_controller.rb
class CombinisController < ApplicationController
  before_action :set_combini, only: [:show, :edit, :update, :destroy]

  protect_from_forgery :except => :create

  # GET /combinis
  # GET /combinis.json
  def index
    @combinis = Combini.all
    respond_to do |format|
      format.html
      format.json { render json: @combinis }
    end
  end

  # GET /combinis/1
  # GET /combinis/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @combini }
    end
  end

  # GET /combinis/new
  def new
    @combini = Combini.new
  end

  # GET /combinis/1/edit
  def edit
  end

  # POST /combinis
  # POST /combinis.json
  def create
    @combini = Combini.new(combini_params)

    respond_to do |format|
      if @combini.save
        format.html { redirect_to @combini, notice: 'Combini was successfully created.' }
        format.json { render action: 'show', status: :created, location: @combini }
      else
        format.html { render action: 'new' }
        format.json { render json: @combini.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combinis/1
  # PATCH/PUT /combinis/1.json
  def update
    respond_to do |format|
      if @combini.update(combini_params)
        format.html { redirect_to @combini, notice: 'Combini was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @combini.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combinis/1
  # DELETE /combinis/1.json
  def destroy
    @combini.destroy
    respond_to do |format|
      format.html { redirect_to combinis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combini
      @combini = Combini.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combini_params
      #params.require(:combini).permit(:user_id, :typegroup_id, :type_id, :neighborhood_id, :name, :comment, :latitude, :longitude, :quality_rank)
      params
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
		  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
    respond_to do |format|
      format.html
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @type }
    end
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @type }
      else
        format.html { render action: 'new' }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params[:type]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  
  #def index
  #  @users = User.all
  #  respond_to do |format|
  #    format.html
  #    format.json { render json: @users }
  #  end
  #end

  def login
    @valid_users = User.where(email: params[:email], password: params[:password])
    respond_to do |f|
      if @valid_users.count == 1
        f.json { render json: @valid_users.take}
      else
        f.json {  render json: @valid_users, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  # GET /users/new
  #def new
  #  @user = User.new
  #end

  # GET /users/1/edit
  #def edit
  #end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  #def destroy
  #  @user.destroy
  #  respond_to do |format|
  #    format.html { redirect_to users_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.require(:user).permit(:name, :email, :password, :motto, :avatar)
      params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/combinis_helper.rb
module CombinisHelper
end

app/helpers/typegroups_helper.rb
module TypegroupsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/combinis/_form.html.erb
<%= form_for(@combini) do |f| %>
  <% if @combini.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@combini.errors.count, "error") %> prohibited this combini from being saved:</h2>

      <ul>
      <% @combini.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :user_id %>:
    <%= f.text_field :user_id %><br>

    <%= f.label :typegroup_id %>:
    <%= f.text_field :typegroup_id %><br>

    <%= f.label :type_id %>:
    <%= f.text_field :type_id %><br>

    <%= f.label :neighborhood_id %>:
    <%= f.text_field :neighborhood_id %><br>

    <%= f.label :name %>:
    <%= f.text_field :name %><br>

    <%= f.label :comment %>:
    <%= f.text_field :comment %><br>

    <%= f.label :latitude %>:
    <%= f.text_field :latitude %><br>

    <%= f.label :longitude %>:
    <%= f.text_field :longitude %><br>

    <%= f.label :quality_rank %>:
    <%= f.text_field :quality_rank %><br>


    <%= f.submit %>
  </div>
<% end %>

app/views/combinis/edit.html.erb
<h1>Editing combini</h1>

<%= render 'form' %>

<%= link_to 'Show', @combini %> |
<%= link_to 'Back', combinis_path %>

app/views/combinis/index.html.erb
<h1>Listing combinis</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>User</th>
      <th>TypeGroup</th>
      <th>Type</th>
      <th>Neighborhood</th>
      <th>Name</th>
      <th>Comment</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Quality Rank</th>
    </tr>
  </thead>

  <tbody>
    <% @combinis.each do |combini| %>
      <tr>
        <td><%= combini.id %></td>
        <td><%= combini.user.name %></td>
        <td><%= combini.typegroup.name %></td>
        <td><%= combini.type.name %></td>
        <td><%= combini.neighborhood.name %></td>
        <td><%= combini.name %></td>
        <td><%= combini.comment %></td>
        <td><%= combini.latitude %></td>
        <td><%= combini.longitude %></td>
        <td><%= combini.quality_rank %></td>

        <td><%= link_to 'Show', combini %></td>
        <td><%= link_to 'Edit', edit_combini_path(combini) %></td>
        <td><%= link_to 'Destroy', combini, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New combini', new_combini_path %>

app/views/combinis/new.html.erb
<h1>New combini</h1>

<%= render 'form' %>

<%= link_to 'Back', combinis_path %>

app/views/combinis/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_combini_path(@combini) %> |
<%= link_to 'Back', combinis_path %>